const palette = {
  emerald: '#0D9373',
  emeraldDark: '#087A60',
  emeraldLight: '#E8F5F1',
  gold: '#D4A843',
  goldLight: '#FDF5E6',
  charcoal: '#1A1D23',
  slate: '#2D3139',
  gray100: '#F7F8FA',
  gray200: '#ECEEF2',
  gray300: '#D1D5DC',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  white: '#FFFFFF',
  red: '#EF4444',
  redLight: '#FEF2F2',
  orange: '#F59E0B',
  orangeLight: '#FFFBEB',
  blue: '#3B82F6',
  blueLight: '#EFF6FF',
  purple: '#8B5CF6',
  purpleLight: '#F5F3FF',
  pink: '#EC4899',
  pinkLight: '#FDF2F8',
  teal: '#14B8A6',
  tealLight: '#F0FDFA',
};

export default {
  light: {
    text: palette.charcoal,
    textSecondary: palette.gray500,
    textMuted: palette.gray400,
    background: palette.gray100,
    card: palette.white,
    tint: palette.emerald,
    tintDark: palette.emeraldDark,
    tintLight: palette.emeraldLight,
    accent: palette.gold,
    accentLight: palette.goldLight,
    border: palette.gray200,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.emerald,
    danger: palette.red,
    dangerLight: palette.redLight,
    ...palette,
  },
};
